exports.AUTH_CONSTANTS = {
  default_TTL: 7,
  infinite_TTL: 999,
};

exports.ADMIN_STATUS = {
  STATUS: ['ACTIVE', 'INACTIVE'],
};

exports.PANEL = {
  CSP: 1,
  ANALYTICS: 2,
  FF: 4,
  SMP: 5,
  debuggerMARKETING : 12,
  ADMIN_PANEL: 32,
  AUTOS_PANEL: 20
};

exports.LEVEL = {
  SUPER_ADMIN: 11,
  ADMIN: 10,
  CITY_SUPPLY_MANAGER: 9,
  ASSISTANT_MANAGER: 12,
  SENIOR_EXECUTIVE: 13,
  EXECUTIVE: 1,
  PAYMENT_EXECUTIVE: 1,
  AUDIT_EXECUTIVE: 1,
  RECOVERY_EXECUTIVE: 1,
  SUPPLY_EXECUTIVE: 1,
  INVENTORY_EXECUTIVE: 1,
  ENROLMENT_AGENT: 2,
  ALL: -1,
  TEAM_LEAD: 5,
  REGULAR: 0
};