exports.REQUIRED_DOCS = {
  MANDATORY_FOR_REGISTRATION: 3,
  MANDATORY_FOR_DRIVING: 1,
  OPTIONAL: 0,
  REQUIRED: 4,
};

exports.DOCUMENT_CATEGORY = {
  DRIVER_DOCUMENT: 0,
  VEHICLE_DOCUMENT: 1,
  FLEET_VEHICLE_DOCUMENT: 2,
};

exports.DOCUMENT_STATUS = {
  APPROVED: 3,
  PENDING: 1,
  REJECTED: 2,
  UPLOADED: 4,
  NOT_UPLOADED: 0,
  EXPIRED: 5,
};

exports.ENROLLED_DOC_STATUS = {
  DOCUMENTS_PENDING: 0,
  VERIFICATION_PENDING: -1,
  VERIFIED: 1,
};
